### ISSUE TITLE
Le fil RSS est en 404

### ISSUE THREAD

**Issue by thom4parisot** [clairezed/portfolio-v2#3]
Le code source de le page indique un fil RSS à l'adresse https://www.clairezuliani.com/feed.xml.

Pourtant ce document est inaccessible :

```bash
$ curl --head https://www.clairezuliani.com/feed.xml
HTTP/2 404
```

Je cherchais à m'abonner au fil RSS de tes weeknotes :-)

**Comment by clairezed** [comment]
Ca devrait être mieux ?

**Comment by thom4parisot** [comment]
Yes ! Ce sont des Lorem Ipsum, c'est normal ?

<img width="1552" alt="Screenshot 2020-01-12 at 22 17 22" src="https://user-images.githubusercontent.com/138627/72225755-5b7e0a80-3589-11ea-8be9-83d571a2475e.png">

**Comment by clairezed** [comment]
Tiens ? J'avais des vieux `posts` fantoches qui traînaient...
Pour les weeknotes, ça se passera ici https://www.clairezuliani.com/feed/weeknotes.xml  (pour le moment, en tout cas)

**Comment by thom4parisot** [comment]
Ouééééé 😄 

C'est tout bon :-)
